#!/usr/bin/env python3
import sys
import argparse
import logging
from pathlib import Path

# --- Configuración del Path ---
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from tpt_project.core.package_manager import PackageManager
from tpt_project.core.config import Configuracion
from tpt_project.utils.logging_config import setup_logging
from tpt_project.cli import CLI

def main():
    """Punto de entrada principal para el ejecutable de TPT."""

    parser = argparse.ArgumentParser(description="TPT Backend CLI")
    parser.add_argument('--debug', action='store_true', help='Activar salida de depuración.')

    # Este parser inicial solo busca el modo debug
    args, remaining_argv = parser.parse_known_args()

    # Configurar el logger
    logger = setup_logging(debug=args.debug)

    try:
        config = Configuracion()
        pm = PackageManager(config, logger)
        cli = CLI(pm, logger)
        # Pasamos los argumentos restantes a la CLI principal para que los procese
        cli.run(remaining_argv)

    except Exception as e:
        logger.critical(f"Error crítico en TPT: {e}", exc_info=True)
        sys.exit(1)

if __name__ == "__main__":
    main()
