#!/usr/bin/env python3
import sys
from pathlib import Path

# Añadir el directorio del proyecto al sys.path
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

# Importar y ejecutar la GUI del asistente
# (La lógica se añadirá más tarde)
from tpt_project.setup.main import run_setup_gui

if __name__ == "__main__":
    # run_setup_gui()
    print("Asistente de configuración (aún no implementado)")
    pass
