name: Update Repository Index

on:
  push:
    branches:
      - regular

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python .github/scripts/update_repository_index.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: Automatically update repository index"
          branch: regular
          file_pattern: index.json
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
